from .function_input import FunctionInput, FunctionInputNumber
from .function_input_translation import FunctionInputTranslation
from .function_input_array import FunctionInputArray
from .function_input_music import FunctionInputSong, FunctionInputSongOR
from .function_input_task import FunctionInputTask
